#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#

'''
Reload ICE Gauntlet authorization server data
'''

import os
import sys
import signal

import psutil


EXIT_OK = 0
EXIT_ERROR = 1


def auth_server_pid():
    '''
    Search for a running auth_server and get PID
    '''
    for proc in psutil.process_iter():
        if proc.name().startswith('python3'):
            for arg in proc.cmdline():
                if arg.startswith('./'):
                    arg = arg[2:]
                if arg == 'auth_server':
                    return proc.pid
    return None


def main():
    '''
    Send SIGUSR1 to running server
    '''
    server_pid = auth_server_pid()
    if not server_pid:
        print('ERROR: auth server process not found. Is the server running?')
        return EXIT_ERROR
    os.kill(server_pid, signal.SIGUSR1)
    return EXIT_OK


if __name__ == '__main__':
    sys.exit(main())
